config/routes.rb
Rails.application.routes.draw do
resources :users, except: [:index]
resources :questions do
  resources :answers
end
get "/sessions" => "sessions#destroy"
resources :sessions, only: [:new, :create, :destroy]
root "sessions#new"

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  require 'redcarpet'
  require 'redcarpet/render_strip'
  paginates_per 10
  validates :question, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :questions
  has_secure_password
  validates :email, uniqueness: true
  validates :email, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_question, only: [:create, :edit, :destroy]
  before_action :find_answer, only: [:destroy]

  def new

  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
      redirect_to question_path(@question)
    else
      render "questions/show"
    end
  end

  def destroy
    @answer.delete
    redirect_to question_path(@question)
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authorize!
    unless current_user
      redirect_to new_user_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize!, except: [:index]
  before_action :find_question, only: [:show, :destroy, :edit, :update]

  def index
    @questions = Question.all.page params[:page]
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = session[:user_id]
    if @question.save
      redirect_to question_path(@question)
    else
      render "new"
    end
  end

  def answer
    @answer = Answer.new
  end

  def show
    @question
    @answer = Answer.new
  end

  def destroy
    @question.delete
    redirect_to questions_path
  end

  def edit
    @question
  end

  def update
    @question.update(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      render "edit"
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :question)
  end

  def find_question
    @question = Question.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @current_session = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if @current_session
      session[:user_id] = @current_session.id
      redirect_to questions_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to questions_path
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
  options = {
    filter_html:     true,
    hard_wrap:       true,
    link_attributes: { rel: 'nofollow', target: "_blank" },
    space_after_headers: true,
    fenced_code_blocks: true
  }

  extensions = {
    autolink:           true,
    superscript:        true,
    disable_indented_code_blocks: true
  }

  renderer = Redcarpet::Render::HTML.new(options)
  markdown = Redcarpet::Markdown.new(renderer, extensions)

  markdown.render(text).html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/answers/new.html.erb
<%= render 'questions/show' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnswerBox2</title>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to "logout", sessions_path %>
      <%= link_to "Profile", current_user %>
    <% else %>
      <%= link_to "Login", new_session_path %>
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <%= link_to "Home", questions_path %>
    <%= yield %>
  </body>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/questions/_form.html.erb
<% if @question.errors.any? %>
  <ul>
  <% @question.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @question do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :question %>
  <%= f.text_area :question, class: 'text' %>
  <br>
  <%= f.submit %>

<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>

<%= render "form", question: @question %>

app/views/questions/index.html.erb
<h1>List of questions</h1>
<%= link_to "New Question", new_question_path %>
<br><br>

<% @questions.each do |question|%>
  <%= question.title %>
  <%= link_to "Show", question_path(question) %>
  <% if question.user_id === current_user.id %>
    <%= link_to "Delete", question, method: :delete %>
  <% end %>
  <br>
<% end %>

app/views/questions/new.html.erb
<h1>Ask a new question</h1>

<% render "new", question: @question %>

app/views/questions/show.html.erb
<br>
<%= @question.title %>
<%= markdown(@question.question) %>
<%= link_to "Back", questions_path  %>

<% if @question.answers.empty? && (@question.user_id === current_user.id) %>
  <%= link_to "edit", edit_question_path(@question) %>
<% else %>
  <% @question.answers.each do |answer|%>
  <% if (current_user.id === answer.user_id) && answer.id %>
    <h3>Answer by <%= answer.user.name %></h3>
    <%= markdown(answer.body) %>
    <%= link_to "Delete", question_answer_url(@question, answer), method: :delete %>
    <% end %>
    <br>
  <% end %>
<% end %>
<% if current_user.id != @question.user_id %>
<h1>Add Answer</h1>
   <%= form_for [@question, @answer] do |f| %>
   <% if @answer.errors.any? %>
     <ul>
     <% @answer.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   <% end %>
   <%= f.label :body %>
   <%= f.text_area :body %>

   <%= f.submit %>
  <% end %>

<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit %>

<% end %>